language: rust
sudo: required
dist: trusty

os:
  - linux

rust:
  - stable
  - beta
  - nightly

script:
  - make --version
  - make tests
  - make suites

matrix:
  allow_failures:
    - rust: nightly
