language: rust
cache: cargo
sudo: required
dist: trusty

os:
  - linux

rust:
  - stable
  - beta
  - nightly

script:
  - make --version
  - make tests suites checks -j 2

matrix:
  allow_failures:
    - rust: nightly
