[workspace]
members = [
  "core",
  "semck",
  "parser",
  "repository",
  "server",
  "cli",
  "backend",
  "backend/doc",
  "backend/java",
  "backend/js",
  "backend/json",
  "backend/python",
  "backend/rust",
]

exclude = [
  "it",
]
