[workspace]
members = [
  "core",
  "manifest",
  "semck",
  "parser",
  "repository",
  "server",
  "cli",
  "pack",
  "backend",
  "backend/doc",
  "backend/java",
  "backend/js",
  "backend/json",
  "backend/python",
  "backend/rust",
]

exclude = [
  "it",
]

[patch.crates-io]
semver = {git = "https://github.com/udoprog/semver", branch = "wildcard"}
semver-parser = {git = "https://github.com/udoprog/semver-parser", branch = "wildcard"}
