[workspace]
members = [
  "lib/core",
  "lib/manifest",
  "lib/semck",
  "lib/parser",
  "lib/repository",
  "server",
  "cli",
  "pack",
  "lib/backend",
  "lib/backend-doc",
  "lib/backend-java",
  "lib/backend-js",
  "lib/backend-json",
  "lib/backend-python",
  "lib/backend-rust",
]

exclude = [
  "it",
]

[patch.crates-io]
semver = {git = "https://github.com/udoprog/semver", branch = "wildcard"}
semver-parser = {git = "https://github.com/udoprog/semver-parser", branch = "wildcard"}
