[package]
name = "reproto"
version = "0.1.1"
authors = ["John-John Tedro <udoprog@tedro.se>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/reproto/reproto"
homepage = "https://github.com/reproto/reproto"
documentation = "https://docs.rs/reproto"
description = """
Rethinking Protocol Generators
"""

[features]
# Enable to emit very detailed tracing, potentially performance sensitive.
tracing = []

[dependencies]
error-chain = "0.10.0"
log = "0.3.7"
clap = "2.24.2"
linked-hash-map = "0.4.2"
serde_json = "1.0.2"
pulldown-cmark = "0.0.14"
ansi_term = "0.9.0"

[dependencies.reproto_core]
version = "0.0.0"
path = "./core"

[dependencies.reproto_parser]
version = "0.0.0"
path = "./parser"

[dependencies.reproto_repository]
version = "0.0.0"
path = "./repository"

[dependencies.reproto_backend]
version = "0.0.0"
path = "./backend"

[dependencies.reproto_backend_java]
version = "0.0.0"
path = "./backend/java"

[dependencies.reproto_backend_js]
version = "0.0.0"
path = "./backend/js"

[dependencies.reproto_backend_json]
version = "0.0.0"
path = "./backend/json"

[dependencies.reproto_backend_doc]
version = "0.0.0"
path = "./backend/doc"

[dependencies.reproto_backend_rust]
version = "0.0.0"
path = "./backend/rust"

[dependencies.reproto_backend_python]
version = "0.0.0"
path = "./backend/python"
