[package]
name = "reproto"
version = "0.1.1"
authors = ["John-John Tedro <udoprog@tedro.se>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/reproto/reproto"
homepage = "https://github.com/reproto/reproto"
documentation = "https://docs.rs/reproto"
description = """
Rethinking Protocol Generators
"""

[features]
# Enable to emit very detailed tracing, potentially performance sensitive.
tracing = []

[dependencies]
error-chain = "0.10.0"
log = "0.3.7"
clap = "2.24.2"
linked-hash-map = "0.4.2"
toml = "0.4.1"
serde = "1.0.8"
serde_derive = "1.0.8"
pulldown-cmark = "0.0.14"
ansi_term = "0.9.0"
reproto_core = {path = "./core"}
reproto_parser = {path = "./parser"}
reproto_repository = {path = "./repository"}
reproto_backend = {path = "./backend"}
reproto_backend_doc = {path = "./backend/doc"}
reproto_backend_java = {path = "./backend/java"}
reproto_backend_js = {path = "./backend/js"}
reproto_backend_json = {path = "./backend/json"}
reproto_backend_python = {path = "./backend/python"}
reproto_backend_rust = {path = "./backend/rust"}

url = "1.5.1"
url_serde = "0.2.0"
