# default variable set for all themes
[default]
half_margin="5px"
margin="10px"
double_margin="20px"

font_size="14px"
font_family="Roboto, Helvetica, sans-serif"
body_bg="#DDDDDD"
bg="#FFFFFF"

title_bg="#F2F2F2"
title_border_color="#D9D9D9"

packages_bg="#FFFFFF"
type_bg="#FFFFFF"
interface_bg="#FFFFFF"
enum_bg="#FFFFFF"
tuple_bg="#FFFFFF"
service_bg="#FFFFFF"

endpoint_font_size="14px"
endpoint_title_font="Roboto, Helvetica, sans-serif"

get_method_fg="#337AB7"
get_method_bg="#D9EDF7"

post_method_fg="#5CB85C"
post_method_bg="#DFF0D8"

put_method_fg="#ED9C28"
put_method_bg="#FCF8E3"

delete_method_fg="#D9534F"
delete_method_bg="#F2DEDE"

[light]
bg="#FFFFFF"
title_bg="#F2F2F2"

[dark]
bg="#999999"
title_bg="#F2F2F2"
body_bg="#000000"
