[package]
name = "reproto"
version = "0.3.7"
authors = ["John-John Tedro <udoprog@tedro.se>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/reproto/reproto"
homepage = "https://github.com/reproto/reproto"
documentation = "https://docs.rs/reproto"
description = """
reproto compiler
"""

[features]
# Enable to emit very detailed tracing, potentially performance sensitive.
tracing = []

[dependencies]
reproto-core = {path = "../core", version = "0.3"}
reproto-semck = {path = "../semck", version = "0.3"}
reproto-manifest = {path = "../manifest", version = "0.3"}
reproto-parser = {path = "../parser", version = "0.3"}
reproto-repository = {path = "../repository", version = "0.3"}
reproto-backend = {path = "../backend", version = "0.3"}
reproto-backend-doc = {path = "../backend/doc", version = "0.3"}
reproto-backend-java = {path = "../backend/java", version = "0.3"}
reproto-backend-js = {path = "../backend/js", version = "0.3"}
reproto-backend-json = {path = "../backend/json", version = "0.3"}
reproto-backend-python = {path = "../backend/python", version = "0.3"}
reproto-backend-rust = {path = "../backend/rust", version = "0.3"}

relative-path = {version = "0.1", features = ["serde"]}
ansi_term = "0.9"
atty = "0.2"
clap = "2.24"
error-chain = "0.11"
linked-hash-map = {version = "0.5", features = ["serde"]}
log = "0.3"
pulldown-cmark = "0.0.14"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
url = "1.5"
url_serde = "0.2"

[patch.crates-io]
semver = {git = "https://github.com/udoprog/semver", branch = "wildcard"}
semver-parser = {git = "https://github.com/udoprog/semver-parser", branch = "wildcard"}
