paths = ["src"]
output = "output"

[publish]
"com.github" = {version = "3.0.0"}
"io.reproto" = {version = "1.0.0"}

[packages]
"io.reproto.blog" = {version = "^1"}
"io.reproto.toystore" = {version = "^1"}
"com.github.gists" = {version = "^3"}
"com.github.pulls" = {version = "^3"}
